### ISSUE TITLE
Potential method to access image source?

### ISSUE THREAD

**Issue by MimikoMono** [Xatrekak/wallpaperRD#3]
With ntbg.app being a redirect to wallhaven.cc I'm not sure this is actually possible (or it might be more a question for nighttab devs) but  figured I'd ask here first in case you had any ideas -- would there be a method to obtain the image source URL?

I occasionally roll an image I'd like to save or search (to find the artist, or series it's from, etc.). Presently there does not appear to be any way to access the source image.

I've tried looking through the page source / inspect but it doesn't seem like nighttab actually shows it there either. All I can see is the HTTP GET to ntbg.app but of course that's actually a redirect to the image on wallhaven.cc and (at least in my testing) there doesn't appear to be any return headers that could lead you back to the post or actual image URL on wallhaven.cc either.

**Comment by Xatrekak** [comment]
Ill look into to see if there is some standard way for me to return a response message along with the redirect that can be done with FastAPI.

**Comment by Xatrekak** [comment]
So it looks like the problem is that browser throws away all of the redirect response data if the inspect tool isn't already open.

If you have the inspect tool open and reload the page you can see the the redriect URL for the new image but that obviously isn't helpful for the current image you want to capture.

The best way as you surmised would be to open an issue with the nighttab dev and see if they can give you any insight on where the image file is stored and if it is retrievable.

If all else fails I do have access to the url logs, I could implement another endpoint that will return the last URL that was delivered to your IP address, this has a lot of obvious caveats around IP address roaming, NAT, accidentally opening another tab and pulling another image, etc.

**Comment by MimikoMono** [comment]
Cheers will take it up with nighttab devs, thanks for taking a look.
